# Generated by Django 2.1.7 on 2019-02-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
