# Generated by Django 2.1.7 on 2019-02-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0002_auto_20190221_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
