# Generated by Django 2.1.7 on 2019-02-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0004_auto_20190221_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='calendar',
            field=models.BinaryField(default=None),
        ),
    ]
