# Generated by Django 2.1.7 on 2019-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0006_auto_20190221_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calendar',
            field=models.BinaryField(),
        ),
    ]
