# Generated by Django 2.1.7 on 2019-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Luna', '0007_auto_20190221_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calendar',
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
